/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package model;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class TweetKey extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -8842491968547888978L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"TweetKey\",\"namespace\":\"model\",\"fields\":[{\"name\":\"key\",\"type\":\"int\",\"doc\":\"To partition each tweet in a repository\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<TweetKey> ENCODER =
      new BinaryMessageEncoder<TweetKey>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<TweetKey> DECODER =
      new BinaryMessageDecoder<TweetKey>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<TweetKey> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<TweetKey> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<TweetKey>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this TweetKey to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a TweetKey from a ByteBuffer. */
  public static TweetKey fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** To partition each tweet in a repository */
  @Deprecated public int key;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public TweetKey() {}

  /**
   * All-args constructor.
   * @param key To partition each tweet in a repository
   */
  public TweetKey(java.lang.Integer key) {
    this.key = key;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return key;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: key = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'key' field.
   * @return To partition each tweet in a repository
   */
  public java.lang.Integer getKey() {
    return key;
  }

  /**
   * Sets the value of the 'key' field.
   * To partition each tweet in a repository
   * @param value the value to set.
   */
  public void setKey(java.lang.Integer value) {
    this.key = value;
  }

  /**
   * Creates a new TweetKey RecordBuilder.
   * @return A new TweetKey RecordBuilder
   */
  public static model.TweetKey.Builder newBuilder() {
    return new model.TweetKey.Builder();
  }

  /**
   * Creates a new TweetKey RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new TweetKey RecordBuilder
   */
  public static model.TweetKey.Builder newBuilder(model.TweetKey.Builder other) {
    return new model.TweetKey.Builder(other);
  }

  /**
   * Creates a new TweetKey RecordBuilder by copying an existing TweetKey instance.
   * @param other The existing instance to copy.
   * @return A new TweetKey RecordBuilder
   */
  public static model.TweetKey.Builder newBuilder(model.TweetKey other) {
    return new model.TweetKey.Builder(other);
  }

  /**
   * RecordBuilder for TweetKey instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<TweetKey>
    implements org.apache.avro.data.RecordBuilder<TweetKey> {

    /** To partition each tweet in a repository */
    private int key;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(model.TweetKey.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.key)) {
        this.key = data().deepCopy(fields()[0].schema(), other.key);
        fieldSetFlags()[0] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing TweetKey instance
     * @param other The existing instance to copy.
     */
    private Builder(model.TweetKey other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.key)) {
        this.key = data().deepCopy(fields()[0].schema(), other.key);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'key' field.
      * To partition each tweet in a repository
      * @return The value.
      */
    public java.lang.Integer getKey() {
      return key;
    }

    /**
      * Sets the value of the 'key' field.
      * To partition each tweet in a repository
      * @param value The value of 'key'.
      * @return This builder.
      */
    public model.TweetKey.Builder setKey(int value) {
      validate(fields()[0], value);
      this.key = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'key' field has been set.
      * To partition each tweet in a repository
      * @return True if the 'key' field has been set, false otherwise.
      */
    public boolean hasKey() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'key' field.
      * To partition each tweet in a repository
      * @return This builder.
      */
    public model.TweetKey.Builder clearKey() {
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public TweetKey build() {
      try {
        TweetKey record = new TweetKey();
        record.key = fieldSetFlags()[0] ? this.key : (java.lang.Integer) defaultValue(fields()[0]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<TweetKey>
    WRITER$ = (org.apache.avro.io.DatumWriter<TweetKey>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<TweetKey>
    READER$ = (org.apache.avro.io.DatumReader<TweetKey>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
